### ISSUE TITLE
Segmentation fault when using more than one session in a process

### ISSUE THREAD

**Issue by stevehartdata** [paulrzcz/takusen-oracle#12]
A program that uses more than one session in the same process (even one after another) crashes with a segmentation fault when the second session ends.

`takusen-oracle` calls `OCITerminate()` once at the end of every session. According to [the Oracle documentation](https://docs.oracle.com/cd/E11882_01/appdev.112/e10646/oci16rel001.htm#LNOCI17127), however, `OCITerminate()` should only be called once for each process.

`OCITerminate()` is not listed in [the Oracle documentation](https://docs.oracle.com/cd/E11882_01/appdev.112/e10646/oci02bas.htm#LNOCI16219) as a necessary step in terminating an application, so I think it's safe to simply remove the calls to `OCITermiante()` when disconnecting from the database.

**Comment by paulrzcz** [comment]
Thanks for pull request. I am going to merge your PR and publish the new patch version of library.
